### ISSUE TITLE
BE Project Setting

### ISSUE THREAD

**Issue by U-Geon** [kookmin-sw/capstone-2025-25#4]
### Issue 설명

백엔드 프로젝트 세팅

### 작업 상세 내용

1. **Spring Security 설정**

- 주요 기능
  - CSRF 비활성화
  - CORS 설정
  - endpoint 별 접근 권한 설정
  - jwt 토큰 필터 설정

2. **Swagger Configuration 설정**
- JWT 토큰 인증 기능 설정

3. **Redis 설정**
- Configuration
  - API 데이터 캐싱용 / 배치 프로세싱 용 Redis ConnectionFactory 분리
  - ConnectionFactory 별 RedisTemplate 설정
- Api 조회 Cache 기능 설정
  - 최신 마인드맵 데이터 캐싱 (Redis에 저장)
  - Redis에서 최신 마인드맵 데이터 가져오기
- 배치 프로세싱 기능 설정
  - 10초마다 Redis 캐시된 마인드맵을 MongoDB에 저장

4. application.yml 및 private yml 파일 설정
private yaml file은 깃허브에 업로드할 수 없어서 Notion을 통해 공유

```
spring:
  config:
    import:
      - application-db.yml
      - application-jwt.yml
      - application-swagger.yml
      - application-oauth.yml
      - application-config.yml
      - application-actuator.yml
```

| private yaml file 주요 내용 |

- Spring App Config 설정
  - App name
  - Server port
  - FE & BE 서버 URL
- Spring Actuator 설정
- DB 설정
  - MongoDB 설정
  - Redis 설정
- jwt 설정
  - 만료기한
  - secret key
- OAuth2 설정
  

5. JWT 설정
jjwt 라이브러리를 활용하여 JwtProvider 및 JwtAuthenticationFilter 스켈레톤 코드 작성

6. OAuth2 관련 코드 작성
- OAuth2 인증 이후의 SuccessHandler, FailureHandler 필터의 스켈레톤 코드 작성
- 그 외 필요한 로직은 담당 팀원의 코드 작성을 위해 생략
